[build]
  publish = ".next"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-lighthouse,netlify-purge-cloudflare-on-deploy"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 3000
