[build]
  publish = ".next"
  command = "npm run build"
[[headers]]
  for = "/*"
    [headers.values]
    X-Robots-Tag = "all"
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  package = "netlify-purge-cloudflare-on-deploy"
[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 3000
