name: Build and Push Docker Image

permissions: write-all

on:
  workflow_dispatch :
  push:
     branches :
          [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          export VERSION=$(git describe --tags --abbrev=0 | awk -F '[-.]' '{print $1"."$2"."$3+1}')
          docker build -t ghcr.io/steamer-academy/astro-app:$VERSION .
          git tag $VERSION
          docker push ghcr.io/steamer-academy/astro-app:$VERSION
