name: Build and Push Docker Image

permissions: write-all

on:
  workflow_dispatch :

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/steamer-academy/astro-app:latest .
          docker push ghcr.io/steamer-academy/astro-app:latest
